### ISSUE TITLE
Keep copyright notices together

### ISSUE THREAD

**Issue by labarba** [Niemeyer-Research-Group/cuIBM-FSI#1]
The commit 2adca5c hides away the original License notice in a folder and puts a new License file on the root folder of the repo. The proper behavior is to leave the original License file and add a copyright line, leaving the original copyright statement intact.

See, for example:
StackExchange— [If I fork a project on Github that is licensed under MIT, how to I handle the attribution and copyright notice?](http://programmers.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at)

There is also a suggestion to add something like:

```
Copyright for portions of project Foo are held by [original author, year] as part of project Bar. 
All other copyright for project Foo are held by [your name, year].
```

See also the reply on this Issue enter by @nedbat
https://github.com/amitassaraf/pdbi/issues/1
_"... add your name to the list, not remove the existing names."_

So, one License file only, with the notice like this:

```
Copyright (c) 2012-2014 Anush Krishnan, Simon Layton, Lorena Barba
Copyright (c) 2015-2016 Olivier Mesnard, Anush Krishnan, Lorena Barba
Copyright (c) 2016 Christopher Minar and Kyle Niemeyer
```

followed by the full License text.

**Comment by kyleniemeyer** [comment]
Ah, perfect, thank you! 

I was trying to figure out the appropriate way to add our own license while keeping the original, but didn't see this (which now seems obvious). I will likely add that other statement as well, once we change the name to avoid confusion with your cuIBM.

This is corrected in 69c8b56c41ef16de62ddd64c59f7db8a020b9a9f.

On a related note, when we (eventually) publish using our version of cuIBM, we'll register a DOI through something like Zenodo, and the full list of contributors will be included.

**Comment by labarba** [comment]
FYI, it's not considered friendly to change the name in such a way as to _not_ identify the original code.

**Comment by kyleniemeyer** [comment]
I was a little concerned about that and what is considered best practice. I'm happy to follow your suggestion on this. I do want to make sure we always properly credit the original work of you and your students, although I can see how it might not seem like it so far as we've blundered through some of this...

With that in mind, what is the appropriate balance between crediting the original code (via the name, anyways) and properly identifying different versions that may have diverged quite a bit? Of course, name by itself isn't sufficient to identify software, and right now the codes are still quite similar.

At this point, we rely mostly on the I/O and parts of the solver framework (e.g., boundary conditions, body class) but the flow solver and IBM implementation are our original code—though of course based on similar theory. With work in progress on improving the direct forcing scheme for moving bodies and planned work to allow freely moving bodies, both the code and capabilities will continue to diverge.
